// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var y = Pervasives.string_of_int(5) + "HI";

console.log("Hello, BuckleScript and Reason!" + y);

var x = 5;

exports.x = x;
exports.y = y;
/* y Not a pure module */
